spring.application.name=iam_service

server.servlet.context-path=/

server.port=8189

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG

swagger.servers.first=http://localhost:8189
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs